import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { getPool, closePool } from "../src/db.js";

/**
 * Client-side git mirror: export a workspace's ledger + current state into committed repo
 * files (so coordination history is git-durable). The consuming project runs this (CI/cron)
 * and commits the output — the central service never needs write credentials to any repo.
 *   npm run mirror-export -- <workspace-slug> [out-dir=.llm-bus]
 */
async function main(): Promise<void> {
  const slug = process.argv[2];
  const outDir = process.argv[3] ?? ".llm-bus";
  if (!slug) {
    console.error("usage: npm run mirror-export -- <workspace-slug> [out-dir]");
    process.exit(2);
  }

  const pool = getPool();
  const ws = await pool.query<{ id: string }>(
    `SELECT id FROM projects WHERE slug = $1 ORDER BY id LIMIT 1`, // slug is per-owner in v2
    [slug],
  );
  if (ws.rowCount === 0) {
    console.error(`workspace not found: ${slug}`);
    process.exit(1);
  }
  const wsId = ws.rows[0].id;

  const events = await pool.query(
    `SELECT id, ts, actor_name, type, payload FROM events WHERE project_id = $1 ORDER BY id ASC`,
    [wsId],
  );
  const claims = await pool.query<{ sequence: string; formatted: string; by: string }>(
    `SELECT DISTINCT ON (payload->>'sequence') payload->>'sequence' AS sequence,
            payload->>'formatted' AS formatted, actor_name AS by
       FROM events WHERE project_id = $1 AND type = 'claim'
      ORDER BY payload->>'sequence', id DESC`,
    [wsId],
  );
  const tasks = await pool.query<{ id: string; title: string; lane: string | null; owner_name: string | null; status: string }>(
    `SELECT id, title, lane, owner_name, status FROM tasks
      WHERE project_id = $1 AND status <> 'done' ORDER BY id`,
    [wsId],
  );
  const leases = await pool.query<{ surface: string; actor_name: string; expires_at: string }>(
    `SELECT surface, actor_name, expires_at FROM leases
      WHERE project_id = $1 AND released_at IS NULL AND expires_at > now()
      ORDER BY acquired_at DESC`,
    [wsId],
  );

  await mkdir(outDir, { recursive: true });
  await writeFile(
    join(outDir, "ledger.jsonl"),
    events.rows.map((r) => JSON.stringify(r)).join("\n") + "\n",
    "utf8",
  );

  const md: string[] = [
    `# LLM Bus mirror — ${slug}`,
    "",
    "_Generated by mirror-export; do not edit by hand._",
    "",
    "## Latest claims",
    ...claims.rows.map((c) => `- ${c.sequence}: ${c.formatted} (by ${c.by})`),
    "",
    "## Open tasks",
    ...tasks.rows.map(
      (t) =>
        `- #${t.id} [${t.status}] ${t.title}${t.owner_name ? " — " + t.owner_name : ""}${t.lane ? " (" + t.lane + ")" : ""}`,
    ),
    "",
    "## Active leases",
    ...leases.rows.map((l) => `- ${l.surface} — ${l.actor_name} (until ${l.expires_at})`),
    "",
  ];
  await writeFile(join(outDir, "state.md"), md.join("\n") + "\n", "utf8");

  await closePool();
  console.log(
    `mirrored '${slug}': ${events.rowCount} events, ${claims.rowCount} sequences, ${tasks.rowCount} open tasks, ${leases.rowCount} leases -> ${outDir}/`,
  );
}

main().catch((err) => {
  console.error("mirror-export failed:", err);
  process.exit(1);
});
